feat: update readme
SOSCON-TheONE/ONE-vscode-extension-prototype pull request #1
Opened 2021-09-01 08:22 UTC by parkjisu6239

리드미  추가 테스트용 : )

2021-09-01 08:23 UTC, donggillee-dev commented on README.md
> +  - 전역에서 눈금 수 변경 가능
좋은 기능이네요!👍

2021-09-01 08:24 UTC, CODe1995 approved these changes
수고하셨습니다~!

2021-09-01 08:24 UTC, donggillee-dev approved these changes

2021-09-02 01:06 UTC, yesfordev commented on README.md
> +  - 전역에서 눈금 수 변경 가능
와 멋있습니당

2021-09-02 01:13 UTC, CODe5753 commented on README.md
> +  - 전역에서 눈금 수 변경 가능
```suggestion
  - 전역에서 눈금수 변경 가능!!
```
테스트를 위해 코멘트 남깁니다😁

2021-09-02 01:15 UTC, yesfordev approved these changes
수고하셨습니다

2021-09-02 01:15 UTC, yesfordev commented on README.md
> +  - 전역에서 눈금 수 변경 가능
`이렇게 하면 되나요?`

2021-09-02 01:16 UTC, CODe1995 requested changes
rquest changes 테스트입니다

2021-09-02 01:16 UTC, CODe5753 approved these changes
고생하셨습니다 :)

2021-09-02 01:16 UTC, wnsdud4197 approved these changes
LGTM

2021-09-02 01:20 UTC, CODe5753 reviewed
review test

2021-09-02 01:20 UTC, CODe5753 commented on README.md
> +  - 전역에서 눈금수 변경 가능!!
Start a review test

2021-09-02 01:20 UTC, CODe5753 commented on README.md
>    - 패널 여닫기 기능
review comment test

2021-09-02 01:21 UTC, merged